source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DownPicker_Example' do
  pod "DownPicker", :path => "../"
end

target 'DownPicker_Tests' do
  pod "DownPicker", :path => "../"

end

